### PR TITLE
Reduce file access, add StatusNotifierWatcher for KDE

### PR DESCRIPTION
**Pull request by fourstepper**
Closes https://github.com/flathub/com.mattermost.Desktop/issues/19 , improves security.

Possibility of closing https://github.com/flathub/com.mattermost.Desktop/issues/13, needs testing

### CODE REVIEW

**Review by fourstepper — COMMENTED** [review]
This should fix build

**Comment by SemaiCZE** [comment]
Thank you. I used this version for a day and it seems sort of ok. But I don't like that whan I'm saving a file somewhere into my `Documents`, everything seems ok, but the file is not there. That is very confusing in my opinion. The only difference to saving into `Downloads` is that it shows _Download completed_ notification.

For Slack it's different. The app always saves files into `Downloads` and won't let you choose the destination.

I don't want to make people angry and silently drop their files. So in my opinion we should wait until Mattermost Desktop notifies you when you haven't enough permissions to write the file into the selected destination or something like that. Does that make sense to you?

**Comment by fourstepper** [comment]
Hi, thank you for your time to test and review this. This behaviour is unfortunate, but I would rather perhaps open up the :ro tags on those folders, if possible. I think this would still be quite a big upgrade from the current state of the app having access to all of $HOME while still supporting majority of the use cases.

What do you think?

**Comment by SemaiCZE** [comment]
Can @TingPing or @apollo13 or some other flatpak guru help us to decide?

**Comment by apollo13** [comment]
Hi Petr, 

I am everything but a flatpak expert but I do have a similar problem with the Signal flatpak app. This one has the rw permissions set to xdg-downloads (IIRC) and saving a file somewhere else silenty fails. I you ask me this is an UX nightmare.

I have the weird feeling that this is something that would need addressing in Electron (?) so file save/read would use portals which shouldn't require the permissions (at least if I understood portals correctly). I'll be interested to hear what the actual flatpak gurus say.

Thanks for the fish^Wping

**Comment by barthalion** [comment]
If it's broken in a not visible way, I don't think we want to go with this.

**Comment by vchernin** [comment]
[Electron 14](https://www.electronjs.org/docs/tutorial/electron-timelines) will let apps use the [xdg-desktop-portal file chooser ](https://github.com/electron/electron/pull/19159) which should eliminate the need to grant Mattermost any system file access. Users will be able to choose any file/folder securely through the use of the portal. Currently Mattermost is on Electron 12. 

In the meantime, for those who want to grant Mattermost Flatpak more file access, I recomend either using the command line `flatpak` tools or using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal).

"--talk-name=org.kde.StatusNotifierWatcher" appears to have been [added elsewhere](https://github.com/flathub/com.mattermost.Desktop/pull/22), so this branch probably isn't needed.

**Comment by fourstepper** [comment]
I dont think this is needed anymore, closing

**Comment by TingPing** [comment]
I'm confused by the closing.

Electron now added proper save dialog support, so surely now is the time to actually do this.

When Mattermost updates to Electron 14 of course

**Comment by TingPing** [comment]
It sounds like the portal isn't being used for some reason.

**Comment by fourstepper** [comment]
Just letting you guys know that I don't use mattermost anywhere anymore and currently don't really have a linux system handy, so it's up to you :) I will watch the thread and be happy to edit the PR as needed, though :)

**Comment by SemaiCZE** [comment]
Hi @fourstepper, thanks. I'd close this PR since I don't want to merge it anytime soon and I'd keep track of home permissions in issue #19.

**Comment by fourstepper** [comment]
@SemaiCZE ok, closing :)

**Pull request closed without merging**
