### PR TITLE
Build with PipeWire support (stable branch)

### PR DESCRIPTION
**Pull request by vchernin**
Fixes screen sharing on Wayland.
See https://github.com/flathub/com.slack.Slack/pull/118.

Steps:

- [x] 1. Update beta branch to latest RC with Electron 12. #25
- [x] 2. Merge PipeWire support into beta branch. #26
- [x] 3. Prepare to merge PipeWire support into stable branch. (this PR, only merge when v4.7.0 is released) (now ready)

If your Mattermost deployment [includes an app that screen shares](https://docs.mattermost.com/deployment/video-and-audio-calling.html), please install the beta branch and attempt to screen share on Wayland.

Note, PipeWire screencasting functionality was never explictly tested, as we didn't have access to an app that screen shares from within Mattermost desktop.

If you want to test this change please test the beta branch.
```bash
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta com.mattermost.Desktop
```

### CODE REVIEW

**Comment by SemaiCZE** [comment]
Hi @vchernin,
thanks for the PR. Did you test it? Don't you need to update the desktop exec command https://github.com/flathub/com.mattermost.Desktop/blob/master/com.mattermost.Desktop.json#L39 with `--enable-features=WebRTCPipeWireCapturer` flag like the Slack?

**Comment by vchernin** [comment]
> Hi @vchernin,
> 
> thanks for the PR. Did you test it? Don't you need to update the desktop exec command https://github.com/flathub/com.mattermost.Desktop/blob/master/com.mattermost.Desktop.json#L39 with `--enable-features=WebRTCPipeWireCapturer` flag like the Slack?

Yeah, you're right, I'm going to change the desktop file too.

The reason I haven't yet is because I haven't actually been able to test screen sharing yet. I looked through [the list of Mattermost calling plugins](https://docs.mattermost.com/deployment/video-and-audio-calling.html), and I don't really have easy access to most of them. The only one I could actually test, Jitsi, can't screen share, [it has a bug](https://github.com/mattermost/mattermost-plugin-jitsi/issues/121) preventing it from sharing on any platform. Side note I've actually encountered the same issue with [Element](https://github.com/vector-im/element-web/issues/4880) so it seems like a common embedded Jitsi bug.

If you are anyone else is able to test this PR (once I've pushed that last commit) that would be most helpful. Even if no one can I think it's probably ok to merge as we aren't changing anything massive, and I couldn't find any regressions in Slack which has basically the exact same problem.

**Comment by SemaiCZE** [comment]
> The reason I haven't yet is because I haven't actually been able to test screen sharing yet. I looked through [the list of Mattermost calling plugins](https://docs.mattermost.com/deployment/video-and-audio-calling.html), and I don't really have easy access to most of them. The only one I could actually test, Jitsi, can't screen share, [it has a bug](https://github.com/mattermost/mattermost-plugin-jitsi/issues/121) preventing it from sharing on any platform. Side note I've actually encountered the same issue with [Element](https://github.com/vector-im/element-web/issues/4880) so it seems like a common embedded Jitsi bug.

Yeah, Mattermost instance at my work (which is the reason I got into flatpacking the app) has only Zoom integration and it basically just generates the links for the Zoom app, no other connection to the Mattermost.

> Edit: I will also add on the current [release version is on Electron 7](https://github.com/mattermost/desktop/blob/v4.6.2/package.json#L57), which almost certainly isn't enough for PipeWire. I think we could just test the beta branch though, since [that should be on Electron 12](https://github.com/mattermost/desktop/pull/1604).

Sure, we can upgrade the Electron. We can also do some releases on the `beta` branch if you want, that's not a problem.

**Comment by vchernin** [comment]
See this PR's description for an overview of what I'm doing now.

I'm currently working on getting #25 working. It appears the upstream location of the icon.svg file was changed, and I've been trying to figure out how exactly. When that's fixed hopefully #25 should work.

When that's done @SemaiCZE could you merge #25 and #26?
Once those are done I think we can wait until mattermost updates their stable builds, and then we should merge this PR (#24). 

There isn't really a point to this PR (#24) until Mattermost updates their Electron version.

**Comment by SemaiCZE** [comment]
@vchernin I've just made the icon to work and merged your PR's into the beta branch. Please test that too:

```
flatpak --user install https://dl.flathub.org/build-repo/48683/com.mattermost.Desktop.flatpakref
```

For me the basic things seems to work ok.
Thanks!

**Comment by vchernin** [comment]
@SemaiCZE That repo seems to work for me as well, thanks for fixing the icon!

I also made #27 to update the beta branch to the latest RC.

**Comment by SemaiCZE** [comment]
Well, I don't know if it's the best fix possible, but I really don't want to dig out the icon from some binary resource file. I guess I can handle to keep the icon inside the repo :slightly_smiling_face:

**Comment by vchernin** [comment]
Seems to be fine for me (I can't actually test logged in behaviour anymore as my free trial ran out, but I'd be surprised if anything broke since last time).

@SemaiCZE This PR should be ready to merge now. I still can't say if PipeWire screen sharing support is actually useful, since neither of us have access to apps that try to screen share from within Mattermost itself. There really isn't any downside though as far as I'm aware.

Note when Mattermost is released with Electron 13, we should update PipeWire to 0.3. [Starting with Electron 13/Chromium 91 PipeWire 0.3 is build by default](https://bugs.chromium.org/p/chromium/issues/detail?id=1146942#c13), so like [Chromium](https://github.com/flathub/org.chromium.Chromium/pull/88/commits/9ba724c2c3127f0e5e50b18d5fe3eb9e4ac225a8), Mattermost should probably use it too.

I also might make another PR to enable Wayland support by default and to see if Mattermost can be updated via x-checker-data.

**Comment by SemaiCZE** [comment]
@vchernin sorry, but I'll get into this after the weekend. Now I'm really busy organizing wild water races.

**Comment by vchernin** [comment]
@SemaiCZE No worries at all, wild water races sounds fun!

**Comment by SemaiCZE** [comment]
@vchernin  It's published. Thank you for your work.

**Pull request merged**
